version: '3.9'

services:
    backend:
        build: .
        volumes:
            - ..:/home/node/tcc_animmendation/backend
            - datasets:/home/node/tcc_animmendation/backend/datasets
        ports:
            - 3000:3000
        command: tail -f /dev/null
        extra_hosts:
            - host.docker.internal:host-gateway
        env_file: ../.env
        tty: true
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:15
        ports:
            - ${DB_PORT:-5432}:5432
        environment:
            POSTGRES_USERNAME: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - dbdata:/var/lib/postgresql/data
            - datasets:/datasets
        healthcheck:
            test: pg_isready -U $$POSTGRES_USERNAME  -d $$POSTGRES_DB
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 5s

volumes:
    dbdata:
    datasets:


